version: '3.5'

services:
  # App Service
  db:
    image: postgres:13
    container_name: bookshelf-postgres
    env_file:
      - ./.env
    volumes:
       - db-data:/var/lib/postgresql/data:delegated
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: always

  migrations:
    container_name: postgres-migrations
    image: migrate/migrate
    volumes:
      - ./app/database/migrations:/app/database/migrations
    command: -source=file://../app/database/migrations -database postgres://docker:docker@db:5432/bookshelf?sslmode=disable up
    restart: on-failure
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - postgres


  app:
    container_name: bookshelf-api
    # Configuration for building the docker image for the service
    build:
      context: . # Use an image built from the specified dockerfile in the current directory.
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # Forward the exposed port 8080 on the container to port 8080 on the host machine
    restart: always
    environment:
      - PGDATABASE=bookshelf
      - PGUSER=docker
      - PGHOST=postgres
      - PGPASSWORD=docker
    volumes:
      - app:/app
    depends_on:
      - db # This service depends on postgres. Start that first.
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - postgres

  pgadmin:
    container_name: bookshelf_pgadmin
    image: dpage/pgadmin4
    env_file:
      - ./.env
    volumes:
       - pgadmin:/root/.pgadmin
    ports:
      - "5555:80"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
  app:
  postgres:
  pgadmin:
  db-data:
