// Code generated by sqlc. DO NOT EDIT.

package database

import (
	"database/sql"
	"time"
)

type Book struct {
	ID         int32     `json:"id"`
	Title      string    `json:"title"`
	Author     string    `json:"author"`
	CoverImage string    `json:"cover_image"`
	InStock    bool      `json:"in_stock"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`
}

type BorrowedBook struct {
	ID           int32        `json:"id"`
	BookID       int32        `json:"book_id"`
	FriendID     int32        `json:"friend_id"`
	BorrowedDate time.Time    `json:"borrowed_date"`
	ReturnedDate sql.NullTime `json:"returned_date"`
	CreatedAt    time.Time    `json:"created_at"`
	UpdatedAt    time.Time    `json:"updated_at"`
}

type Friend struct {
	ID        int32     `json:"id"`
	FullName  string    `json:"full_name"`
	Photo     string    `json:"photo"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}
